### PR TITLE
Fixed to be able to use Tab key for IME candidate selection

### PR DESCRIPTION
**Pull request by hantabaru1014**
When typing Japanese, type alphabet corresponding to the Japanese you wish to input, select the desired character from the candidates the IME produces, and type it in.
The Tab key is used to select the candidate, but I could not use it with this mod installed.
So, I made it so that the Tab key does not respond when the IME is in select a candidate.

### CODE REVIEW

**Comment by Banane9** [comment]
ohhh, thank you for adding this - this never crossed my mind as I've never used that sort of input method before!

**Comment by Banane9** [comment]
Now, for some reason for me the references aren't working properly with multiple hint paths.  
Tried this:
Reference Definitions

But for some reason the NML and Harmony references keep failing, despite the FrooxEngine one working.
Referenced DLLs

And the files exist in /Libraries/NeosModLoader.dll and /0Harmony.dll

**Comment by kazu0617** [comment]
(I think harmonylib doesn't need actual dll.
`<PackageReference Include="Lib.Harmony" Version="2.2.1" />`

**Comment by Banane9** [comment]
sls on discord had the deciding hint - I forgot that I had the standalone version installed too but without mods, which made it use the wrong path

**Pull request merged**
